services:
  - type: web
    name: clothverse
    runtime: python3
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn clothverse.wsgi:application --bind 0.0.0.0:$PORT
